export default [
    {
        id: 0,
        img:"/product__1.jpg",
        name:"wild silk finish Lipstic",
        price:41.0,
        categorey:["lipstics"],
        sale:false,
    },
    {
        id: 1,
        img:"/product__2.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["lipstic"],
        sale:false,
    },
    {
        id: 2,
        img:"/product__3.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["lipstic","makeup"],
        sale:false,
    },
    {
        id: 3,
        img:"/product__4.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["skincare"],
        sale:false,
    },
    {
        id: 4,
        img:"/product__5.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["lipstic"],
        sale:false,
    },
    {
        id: 5,
        img:"/product__6.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["lipstic"],
        sale:false,
    },
    {
        id: 6,
        img:"/product__7.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["lipstic"],
        sale:false,
    },
    {
        id: 7,
        img:"/product__8.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["lipstic"],
        sale:false,
    },
    {
        id: 8,
        img:"/product__9.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["lipstic"],
        sale:false,
    },
    {
        id: 9,
        img:"/product__10.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["lipstic"],
        sale:false,
    },
    {
        id: 10,
        img:"/product__11.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["lipstic"],
        sale:false,
    },
    {
        id: 11,
        img:"/product__12.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["lipstic"],
        sale:false,
    },
    {
        id: 12,
        img:"/product__13.jpg",
        name:"wild silk fashion lipstic",
        price:41.0,
        category:["lipstic"],
        sale:false,
    },
   
]